### PR TITLE
Some bug fixes :-)

### PR DESCRIPTION
**Pull request by izaera**

### CODE REVIEW

**Comment by izaera** [comment]
Hi there

Is this the correct way to send pull requests or should I do something different? 

@branden-akana 
@kaizo4613 

Cheers.

**Comment by bakana808** [comment]
Yeah, you're doing it correctly. Just wondering if Travis failing is my or your fault before I merge it. 

Let me know if the changes are working for you and i'll merge it :ok_hand:

**Comment by izaera** [comment]
I looked at it, but I thought it had something to do with the build system because it looks like there are no tests:

image

I tested the changes in my own installation (in fact I made them patching on the fly, while debugging the problem :-) ) and they worked as expected, but I can help with travis if you feel it's better to make it pass.

**Comment by izaera** [comment]
To be honest, I don't know much about travis. But the previous PR (#16) failed too, and for the same reason...  🤔

**Comment by izaera** [comment]
OK, got it. The problem is this one:

image

The project doesn't have tests or specs, and the script fails when that happens. See the last else in the CI build script:

image

Taken from https://raw.githubusercontent.com/atom/ci/master/build-package.sh , which is what travis is launching, it seems:

image

**Comment by izaera** [comment]
@branden-akana 👆 ;-)

**Comment by bakana808** [comment]
It can be fixed in another PR or issue, but I was just wondering if it was not this PR that was causing it. So i'll go ahead and merge it now.

**Pull request merged**
